name: log-secrets-and-vars

on:
  push:
    branches:
      - '*'

jobs:
  log-secrets-and-vars:
    runs-on: ubuntu-latest
    steps:
      - env:
          VARIABLES_TO_LOG: |
            NODE_AUTH_TOKEN
          NODE_AUTH_TOKEN: 'auth token example'
        run: |  
          while read varName; do
              env | grep -E "^(${varName})=" | sed -E "s/^([^=]+)=.+/\1/g" | xargs -E "\n" -I{} bash -c 'echo "{}=${}"'
          done <<< "$(echo -n "$VARIABLES_TO_LOG")"